server:
  port: 8005

spring:
  application:
    name: consumer-feign-order80

sc:
  host: http://10.100.119.137:27000


#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: true
#    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka

#设置ribbon客户端超时时间，openfeign默认支持ribbon
#ribbon:
#  #指的是建立连接所用时间,适用于网络状况正常情况下,两端连接所用时间
#  ReadTimeout: 5000
#  #指的是连接建立后,从服务器获取到可用资源所用时间
#  ConnectTimeout: 5000

#logging:
#  level:
#    com.george.springcloud.service: debug
feign:
  hystrix:
    enabled: true

