#项目对外提供的端口号
server:
  port: 8088

#服务别名，注册到zookeeper的注册中心的名称
spring:
  application:
    name: consumer-order-zk80
  cloud:
    zookeeper:
      connect-string: 120.24.162.8:2181
  profiles:
    include: common



