server:
  port: 8001


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

spring:
  application:
    name: provider-hystrix-payment8001
  profiles:
    include: common
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1

